"use client";

import { useState, useTransition } from "react";
import { updatePost, setPublished } from "../actions";
import type { DailyPost } from "../data";

export default function PostEditor({ post }: { post: DailyPost }) {
  const g = post.generated;
  const [hook, setHook] = useState(g?.hook ?? "");
  const [script, setScript] = useState(g?.script ?? "");
  const [caption, setCaption] = useState(g?.caption ?? "");
  const [hashtagsRaw, setHashtagsRaw] = useState(
    (g?.hashtags ?? []).join(" "),
  );
  const [keyword, setKeyword] = useState(g?.keyword ?? "");
  const [body, setBody] = useState(post.body ?? "");
  const [published, setPublishedState] = useState<boolean>(!!post.isPublished);
  const [isPending, startTransition] = useTransition();
  const [status, setStatus] = useState<string | null>(null);
  const [videoFile, setVideoFile] = useState<File | null>(null);

  const togglePublish = () => {
    const next = !published;
    setStatus(null);
    startTransition(async () => {
      const res = await setPublished(post.slug, next);
      if (res.ok) {
        setPublishedState(next);
        setStatus(next ? "published" : "unpublished");
      } else {
        setStatus("failed");
      }
      setTimeout(() => setStatus(null), 1500);
    });
  };

  const save = (patch: Partial<{
    hook: string; script: string; caption: string; hashtags: string[]; keyword: string; body: string;
  }>) => {
    setStatus(null);
    startTransition(async () => {
      const res = await updatePost(post.slug, patch);
      setStatus(res.ok ? "saved" : "save failed");
      setTimeout(() => setStatus(null), 1500);
    });
  };

  const saveHashtags = () => {
    const arr = hashtagsRaw
      .split(/[\s,]+/)
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) => (s.startsWith("#") ? s : "#" + s));
    save({ hashtags: arr });
  };

  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setStatus("copied");
      setTimeout(() => setStatus(null), 1200);
    } catch {
      /* ignore */
    }
  };

  if (!g) {
    return (
      <div className="mt-8 rounded-xl border border-amber-500/30 bg-amber-500/5 p-6 text-sm text-amber-200">
        Content for this guide hasn&apos;t been generated yet. Run{" "}
        <code>python generate_post_content.py --slug {post.slug}</code> in{" "}
        <code>C:\Users\serka\Fadia voice\</code>.
      </div>
    );
  }

  // Your own deployed /guides/<slug> page — this is what ManyChat sends
  // to people who comment the trigger keyword. Hosted on the same domain
  // as the dashboard so we own the click + the read. NEXT_PUBLIC_APP_URL
  // is the canonical origin (set in Vercel + .env); fall back to the
  // current production deployment if it's missing in dev.
  const guideOrigin =
    process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") ??
    "https://creator-os-delta.vercel.app";
  const fadiaUrl = `${guideOrigin}/guides/${post.slug}`;

  // Prefill /compose with the caption + hashtags
  const composeUrl =
    "/compose?prefillCaption=" +
    encodeURIComponent(caption + "\n\n" + hashtagsRaw);

  return (
    <div className="mt-6 space-y-6">
      {/* Status pill + Publish toggle */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-2 text-xs text-[var(--color-muted)]">
          <span>Generated by {post.model ?? "?"}</span>
          {post.generated_at && (
            <span>· {post.generated_at.slice(0, 10)}</span>
          )}
          <span
            className={`rounded border px-1.5 py-0.5 text-[10px] uppercase font-semibold ${
              published
                ? "bg-emerald-500/10 text-emerald-300 border-emerald-500/30"
                : "bg-zinc-500/10 text-zinc-400 border-zinc-500/30"
            }`}
          >
            {published ? "live on /guides" : "draft"}
          </span>
        </div>
        <div className="flex items-center gap-2">
          {status && (
            <span className="text-xs text-emerald-300">{status}</span>
          )}
          {published && (
            <a
              href={`/guides/${post.slug}`}
              target="_blank"
              rel="noreferrer"
              className="rounded border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 px-3 py-1.5 text-xs hover:bg-emerald-500/20"
            >
              View public ↗
            </a>
          )}
          <button
            type="button"
            onClick={togglePublish}
            disabled={isPending}
            className={`rounded px-3 py-1.5 text-xs font-semibold disabled:opacity-50 ${
              published
                ? "border border-[var(--color-border)] bg-[var(--color-surface)] hover:bg-[var(--color-surface-hover)]"
                : "bg-[var(--color-text)] text-[var(--color-text-on-dark)] hover:opacity-90"
            }`}
          >
            {published ? "Unpublish" : "Publish to /guides"}
          </button>
        </div>
      </div>

      {/* Keyword (ManyChat trigger) */}
      <Section label="ManyChat keyword" hint="The trigger users comment to get the link">
        <div className="flex gap-2 items-center">
          <input
            value={keyword}
            onChange={(e) => setKeyword(e.target.value.toUpperCase())}
            onBlur={() => save({ keyword })}
            className="flex-1 max-w-xs rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-base font-mono uppercase"
          />
          <button
            type="button"
            onClick={() => copy(keyword)}
            className="rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-xs hover:bg-[var(--color-surface-hover)]"
          >
            Copy
          </button>
        </div>
      </Section>

      {/* Hook */}
      <Section label="Hook" hint="First 1-2 sentences on camera">
        <textarea
          value={hook}
          onChange={(e) => setHook(e.target.value)}
          onBlur={() => save({ hook })}
          rows={3}
          className="w-full rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm leading-relaxed"
        />
        <ActionBar onCopy={() => copy(hook)} />
      </Section>

      {/* Talking-head script */}
      <Section label="Talking-head script" hint="60-90 seconds, paste into a teleprompter">
        <textarea
          value={script}
          onChange={(e) => setScript(e.target.value)}
          onBlur={() => save({ script })}
          rows={14}
          className="w-full rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm leading-relaxed font-mono"
        />
        <ActionBar onCopy={() => copy(script)} />
      </Section>

      {/* Long-form article body — the "full guide" shown on /guides/<slug>.
          Empty by default; the admin pastes/writes a fuller piece of prose
          here when they want the public page to read as a real article
          (not just hook + script). Blank lines render as paragraph breaks
          on the public page. */}
      <Section
        label="Full guide body"
        hint="Long-form article shown on the public /guides page. Blank line = new paragraph."
      >
        <textarea
          value={body}
          onChange={(e) => setBody(e.target.value)}
          onBlur={() => save({ body })}
          rows={18}
          placeholder="Write or paste the full guide here. This is what visitors read on the public /guides/<slug> page. Leave empty if you only want hook + script + caption on the page."
          className="w-full rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm leading-relaxed"
        />
        <div className="mt-1.5 flex gap-2 items-center">
          <button
            type="button"
            onClick={() => copy(body)}
            className="text-[11px] rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-2 py-1 hover:bg-[var(--color-surface-hover)]"
          >
            Copy
          </button>
          <span className="text-[10px] text-[var(--color-muted)]">
            {body.trim().split(/\s+/).filter(Boolean).length} words · auto-saves on blur
          </span>
          {published && body.trim() && (
            <a
              href={`/guides/${post.slug}`}
              target="_blank"
              rel="noreferrer"
              className="text-[11px] text-[var(--color-blush-deep)] hover:underline ml-auto"
            >
              Preview public page ↗
            </a>
          )}
        </div>
      </Section>

      {/* Caption */}
      <Section label="Instagram caption" hint="150-200 words, ends with the keyword CTA">
        <textarea
          value={caption}
          onChange={(e) => setCaption(e.target.value)}
          onBlur={() => save({ caption })}
          rows={8}
          className="w-full rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm leading-relaxed"
        />
        <ActionBar onCopy={() => copy(caption)} />
      </Section>

      {/* Hashtags */}
      <Section label="Hashtags" hint="Space or comma separated">
        <textarea
          value={hashtagsRaw}
          onChange={(e) => setHashtagsRaw(e.target.value)}
          onBlur={saveHashtags}
          rows={3}
          className="w-full rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm font-mono"
        />
        <ActionBar onCopy={() => copy(hashtagsRaw)} />
      </Section>

      {/* ManyChat reply link → your own /guides/<slug> page */}
      <Section
        label="ManyChat reply link"
        hint="Paste into your ManyChat keyword reply — sends commenters straight to this guide on your site"
      >
        <div className="flex gap-2 items-center">
          <input
            value={fadiaUrl}
            readOnly
            onClick={(e) => (e.target as HTMLInputElement).select()}
            className="flex-1 rounded border border-emerald-500/30 bg-emerald-500/5 px-3 py-2 text-xs font-mono"
          />
          <button
            type="button"
            onClick={() => copy(fadiaUrl)}
            className="rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-xs hover:bg-[var(--color-surface-hover)]"
          >
            Copy URL
          </button>
          <a
            href={fadiaUrl}
            target="_blank"
            rel="noreferrer"
            className="rounded border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 px-3 py-2 text-xs hover:bg-emerald-500/20"
          >
            Open ↗
          </a>
        </div>
        <div className="mt-2 text-[10px] text-[var(--color-muted)]">
          Paste this URL into your ManyChat keyword reply for{" "}
          <code className="font-mono">{keyword || "(no keyword set)"}</code>.
          When someone comments it on your Reel, they get this link in DM.
        </div>
      </Section>

      {/* Video upload slot */}
      <Section label="Talking-head video" hint="Drop your recorded video here">
        <div className="rounded-lg border border-dashed border-[var(--color-border)] bg-[var(--color-surface)] p-6 text-center">
          {videoFile ? (
            <div>
              <div className="text-sm font-medium">{videoFile.name}</div>
              <div className="text-xs text-[var(--color-muted)] mt-1">
                {(videoFile.size / 1024 / 1024).toFixed(1)} MB
              </div>
              <button
                type="button"
                onClick={() => setVideoFile(null)}
                className="mt-3 text-xs text-[var(--color-muted)] underline"
              >
                Remove
              </button>
            </div>
          ) : (
            <label className="cursor-pointer">
              <input
                type="file"
                accept="video/*"
                className="hidden"
                onChange={(e) => setVideoFile(e.target.files?.[0] ?? null)}
              />
              <div className="text-sm text-[var(--color-muted)]">
                Click to select video (or drag here)
              </div>
              <div className="text-xs text-[var(--color-muted)] mt-1">
                MP4 / MOV — typically a 60-90 sec talking-head clip
              </div>
            </label>
          )}
        </div>
      </Section>

      {/* Action bar — post to all */}
      <div className="sticky bottom-4 mt-8 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]/95 backdrop-blur p-4 flex flex-wrap items-center gap-3 shadow-lg">
        <div className="text-sm">
          Ready to publish? Click <strong>Open Compose</strong> to use your
          existing posting pipeline with caption + hashtags prefilled.
        </div>
        <div className="flex-1" />
        <a
          href={composeUrl}
          className="rounded bg-[var(--color-text)] text-[var(--color-text-on-dark)] px-4 py-2 text-sm font-semibold hover:opacity-90"
        >
          Open Compose →
        </a>
      </div>

      {isPending && (
        <div className="fixed bottom-4 left-4 rounded bg-black/60 text-white text-xs px-3 py-1.5">
          Saving…
        </div>
      )}
    </div>
  );
}

function Section({
  label,
  hint,
  children,
}: {
  label: string;
  hint?: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="mb-1.5 flex items-baseline justify-between gap-2">
        <h3 className="text-sm font-semibold">{label}</h3>
        {hint && <span className="text-[10px] text-[var(--color-muted)]">{hint}</span>}
      </div>
      {children}
    </div>
  );
}

function ActionBar({ onCopy }: { onCopy: () => void }) {
  return (
    <div className="mt-1.5 flex gap-2">
      <button
        type="button"
        onClick={onCopy}
        className="text-[11px] rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-2 py-1 hover:bg-[var(--color-surface-hover)]"
      >
        Copy
      </button>
      <span className="text-[10px] text-[var(--color-muted)] self-center">
        edits auto-save on blur
      </span>
    </div>
  );
}
