// Full per-day content for the 30-day plan: talking-head script, complete
// caption, hashtags, and the ManyChat DM auto-reply sent when someone comments
// the day's keyword. plan.ts holds the short briefs; this holds the finished copy.

export type PlanContent = {
  script: string;
  caption: string;
  hashtags: string[];
  dmReply: string;
};

export const PLAN_CONTENT: Record<string, PlanContent> = {
  "ccs-01-what-is-claude-code": {
    script: "What is Claude Code? Welcome to Claude Code Summer. Today we answer one question: what is Claude Code? Most of you know AI chatbots like ChatGPT, Gemini, Claude, and Grok - the ones you ask questions. Claude Code is different: it's an agentic coding tool. It doesn't just answer questions, it helps you code and build things - it can understand your codebase, edit your files, run commands, and plug into the tools you already use. You can use it in your terminal, in an editor like VS Code, in the Claude desktop app, and even on the web. This is what people call an AI agent: at its core it's still talking to a large language model, but now it runs in a loop, in real time, with access to tools and documents - so it skips the copy-and-paste work and takes real actions toward a goal you set. There are three key ideas to use it well - but class is over for today. Comment LEARN and I'll send them to you. See you tomorrow!",
    caption: "Day 1 of Claude Code Summer. What is Claude Code? It's not just a chatbot - it's an AI agent that helps you build: it reads your files, runs commands, and works inside the tools you already use. Comment LEARN for the 3 key ideas to use it well.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said LEARN 🙌 Here's the 3 key ideas to use Claude Code well — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-02-install-claude-code": {
    script: "How to install Claude Code in under two minutes. First, you'll need an account: go to claude.ai, sign up, and grab a Pro or Max plan - I'd start with Pro. Then open the app called Terminal - just search 'Terminal' and you'll see a black screen. Next, head to the Claude Code page (link in comments) and copy the one-line install command for your device. I'm on a Mac, so I copy it, paste it into Terminal, and hit Enter. That's it - Claude Code installs itself. Once installed, type 'claude' and hit Enter to start it. It'll ask you to pick a theme and a few settings - press Enter through them, then press Enter to authenticate. A pop-up appears - click Authorize, and you're in. Save this and comment BUILD to learn how to make your first app in under five minutes.",
    caption: "Day 2 of Claude Code Summer. Install Claude Code in under 2 minutes - even if you've never touched code. Sign up at claude.ai, open Terminal, paste one command, type 'claude,' and authorize. Save it, and comment BUILD for your first app next.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said BUILD 🙌 Here's how to build your first app in under 5 minutes — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-03-how-it-works-the-agentic-loop": {
    script: "How does Claude Code actually work? Meet the agentic loop. Step one: it starts with you - you give Claude Code a prompt, the goal. Step two: it gathers the context it needs by talking to the model, which sends back text or a tool action to run. Step three: it does the job - editing a file, running a command, whatever's needed. Step four: it checks its own work and decides if it did what you asked. If it passes, it waits for your next prompt; if not, it looks back and tries again until it's right. Anytime, you can jump in - add context, interrupt, or steer it. All of this takes memory, stored in the context window - it holds a lot, but not infinitely, which is why Claude Code auto-compacts: trimming what it no longer needs. What sets it apart from a chatbot is tools, and it has permission modes you can set. Comment PERMISSION for a note on the modes.",
    caption: "Day 3 of Claude Code Summer. How does Claude Code actually work? It runs in an 'agentic loop': you set a goal, it gathers context, takes action, then checks its own work - repeating until it's right. Plus memory, tools, and permission modes. Comment PERMISSION for the breakdown.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said PERMISSION 🙌 Here's the simple breakdown of permission modes — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-04-first-prompt": {
    script: "How to prompt Claude Code for the first time. The good news: you talk to it in plain English. But two things make life easier and keep you protected. First, auto-accept edits. When you start, you'll get lots of requests - it wants to access files, run commands. Press Shift+Tab to cycle modes. Auto-accept lets it edit or create files without asking each time, but it still checks before running any command. Next, plan mode - also in that Shift+Tab menu. It uses read-only tools to study your project and research how to build what you asked, asks a few clarifying questions, then hands you a plan: a text file laying out exactly how it'll do the work. I almost always use plan mode to start fresh or before any complex change. Tip: Shift+Tab cycles normal, auto-accept edits, then plan mode. See you next time!",
    caption: "Day 4 of Claude Code Summer. How to prompt Claude Code for the first time - you just talk to it in plain English. Two modes to know: auto-accept edits (fewer interruptions) and plan mode (it researches first, then hands you a plan). Hit Shift+Tab to switch. Save this for your first session.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "",
  },
  "ccs-05-don-t-code-first-explore-plan": {
    script: "Don't let Claude Code write code first. If you open it and immediately say 'build something,' you're signing up for twenty rounds of fixing it later. Use Anthropic's workflow instead: explore, plan, code, commit. Today, the first two. Start in plan mode - Claude won't touch a file, it just reads and thinks; hit Shift+Tab until you see plan mode. Example: 'I want to use my webcam to detect hand gestures and control sound. Figure out the library and the approach.' It reads your files, runs web searches, hands you a plan, and asks questions before writing code. You don't need plan mode to explore, though - if you don't know where to start, type /init and Claude explores your whole codebase. Great for big projects or a repo someone else wrote. Comment WORKFLOW and I'll send you the full flow.",
    caption: "Day 5 of Claude Code Summer. The #1 mistake? Telling Claude Code to build something the second you open it - that's how you fix it 20 times. Use Anthropic's workflow: explore -> plan -> code -> commit. Today: start in plan mode, and use /init to explore any project. Comment WORKFLOW for the full flow.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said WORKFLOW 🙌 Here's the full explore → plan → code → commit workflow — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-06-status-bar": {
    script: "I have a status bar that tells me everything I need while using Claude Code. Four things I watch: my current folder; my Git branch (it says 'main,' so I know where my code goes); the context window bar (how much I've used, so I know when to compact); and which model I'm using. To set it up, go to your terminal, type /statusline, and tell it what you want: the folder, the Git branch, the model name, and the context percentage with a progress bar. Comment STATUS and I'll send you the exact copy-paste prompt.",
    caption: "Day 6 of Claude Code Summer. This little status bar tells me everything at a glance: my folder, my Git branch, how much context I've used (so I know when to compact), and which model I'm running. Set it up in seconds with /statusline. Comment STATUS for the exact prompt.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said STATUS 🙌 Here's the exact /statusline prompt to copy-paste — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-07-claude-md": {
    script: "CLAUDE.md - and how to use it. It's basically a memo file for Claude Code: set your rules and preferences, and Claude reads it at the start of every session, so it knows how to work with you before you say a word. What to put in it? Four powerful rules. One, plan before executing - think through a plan before any non-trivial task, and re-plan if something goes wrong. Two, subagent strategy - use subagents to keep your main context clean, like hiring kitchen staff instead of cooking the whole meal yourself. Three, self-improve - after any correction, it updates its lessons file so it won't repeat the mistake. Four, verify before done - never mark a task complete without proving it works: run the tests, check the logs. To set it up, screenshot this, drop it into Claude Code, and ask it to create the CLAUDE.md file in your root folder. Comment SEND and I'll get you the file.",
    caption: "Day 7 of Claude Code Summer. Meet CLAUDE.md - a memo file Claude Code reads at the start of every session, so it already knows how you work. Four rules that 10x your results: plan before executing, use subagents, self-improve after corrections, and verify before done. Comment SEND for the file.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said SEND 🙌 Here's the ready-to-use CLAUDE.md file — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-08-slash-commands": {
    script: "Slash commands - your shortcuts menu. Here's the trick that makes Claude Code so much easier: slash commands. Any time you're in Claude Code, type the forward slash key - '/' - and a menu pops up. These are instant shortcuts. Here are the five I use most. /help - shows you everything Claude Code can do. /clear - wipes the slate clean and starts a fresh conversation; I use it every time I switch tasks. /compact - tidies up a long session so Claude keeps running smoothly. /diff - shows you every change Claude made this session. /rewind - my safety net: it undoes Claude's changes and takes you back. When in doubt, hit '/' and look. Comment COMMANDS and I'll send you my full slash command cheat sheet. See you tomorrow!",
    caption: "Day 8 of Claude Code Summer. You're not really using Claude Code until you're using slash commands. Type '/' and a menu pops up. My 5 go-tos: /help, /clear (fresh start), /compact (tidy long sessions), /diff (see every change), /rewind (undo + go back). Comment COMMANDS for the full cheat sheet.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said COMMANDS 🙌 Here's my full slash-command cheat sheet — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-09-cost-track-your-spending": {
    script: "Know exactly what you're spending. Here's a command worth knowing: /cost. Type it in your terminal and Claude shows how much you've used in your current session - the tokens, and the running total. Think of tokens as the little units of text Claude reads and writes; every message uses some. /cost lets you watch that add up in real time, so there are no surprises. My habit: I check /cost before a long session, and if it's climbing fast, I run /compact to tidy up and bring it down. Smart builders don't just build - they keep an eye on their usage. Comment COST and I'll send you my simple routine for keeping spend low. See you tomorrow!",
    caption: "Day 9 of Claude Code Summer. Using Claude Code but not watching your spend? Type /cost - it shows your usage and running total for the session, so no surprises. My habit: check /cost before long sessions, and run /compact if it's climbing. Comment COST for my keep-it-low routine.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said COST 🙌 Here's my simple routine for keeping your spend low — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-10-create-your-own-slash-commands": {
    script: "Make your own shortcuts. Yesterday we used built-in slash commands - today you'll make your own. Inside your project, Claude Code keeps a little folder called .claude/commands. Any text file you drop in there becomes your own slash command. For example, save a file called review.md with instructions like 'review my code for mistakes and explain them simply,' and now typing /review runs that whole instruction for you - every time, no retyping. Build one for anything you do often: writing tests, cleaning up files, summarizing your day. And if you work with a team, everyone gets the same commands. This is how you go from using Claude to truly running it. Comment CUSTOM and I'll send you three ready-made commands to start with.",
    caption: "Day 10 of Claude Code Summer. The real power move: make your OWN slash commands. Drop a text file in .claude/commands and it becomes a shortcut you can run anytime - no retyping. Comment CUSTOM for 3 ready-made commands to start with.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said CUSTOM 🙌 Here's 3 ready-made custom slash commands to start with — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-11-permission-modes-incl-hard-deny": {
    script: "Permission modes - how to stay in control. Claude Code always asks before doing certain things, and you decide how much it checks with you. Press Shift+Tab to move between modes. In normal mode, Claude asks before editing files or running commands - safest and most hands-on. In auto-accept edits, it edits and creates files freely but still checks before running commands - great once you trust the plan. And plan mode is read-only: it looks and thinks but never changes anything. There's also a stronger guardrail: you can set certain actions to always be denied - a 'hard deny' - so Claude can never do them, even when working on its own. My advice: start cautious, loosen up as you get comfortable, and keep the risky stuff on hard deny. Comment PERMISSION and I'll send you my mode-by-mode guide.",
    caption: "Day 11 of Claude Code Summer. Stay in control with permission modes. Shift+Tab cycles them: normal (asks first), auto-accept edits (edits freely, still checks before commands), and plan mode (read-only). Plus 'hard deny' for actions Claude should NEVER take. Comment PERMISSION for my mode-by-mode guide.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said PERMISSION 🙌 Here's my mode-by-mode permissions guide — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-12-subagents-your-ai-team": {
    script: "Subagents - your AI team. Instead of one assistant doing everything, Claude Code can spin up subagents - helpers that take on a specific job so your main conversation stays clean and focused. Think of it like hiring specialists: a code reviewer, a security checker, a test writer, a documentation writer, a performance optimizer. You can even give them names so you know who's doing what. You hand off a task - 'have the reviewer check this' - and the subagent goes off, does its research, and reports back, without cluttering your main chat. It's teamwork, AI-style: the right helper for the right job, so Claude works smarter, not harder. Comment AGENTS and I'll send you my starter set of subagents.",
    caption: "Day 12 of Claude Code Summer. Meet subagents - your AI team. Instead of one helper doing everything, spin up specialists: a code reviewer, security checker, test writer, and more, each with a name. Right helper, right job. Comment AGENTS for my starter set.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said AGENTS 🙌 Here's my starter set of subagents — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-13-connect-your-tools-mcp": {
    script: "Connect Claude Code to your other tools. Here's where Claude Code gets really powerful: something called MCP. In plain English, MCP is a way to plug Claude Code into the other apps and services you already use - so it can read and act on real information, not just code on your laptop. Want it to pull from your notes, your files, a database, or a tool your team uses? You connect that tool once, and Claude can work with it directly - no more copy-and-paste back and forth. It's like giving Claude a set of keys to the rooms it's allowed into. Start with one connection you'd use daily and grow from there. Comment CONNECT and I'll send you a beginner-friendly list of tools to try first.",
    caption: "Day 13 of Claude Code Summer. MCP = plugging Claude Code into the apps you already use, so it works with your real info instead of copy-paste. Connect one tool you'd use daily and grow from there. Comment CONNECT for beginner-friendly tools to try first.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said CONNECT 🙌 Here's a beginner-friendly list of tools to connect first — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-14-show-don-t-tell-images-as-input": {
    script: "Show, don't tell. One of my favorite tricks: you don't always have to describe what you want - you can show Claude Code. Got a screenshot of an error message? A picture of a design you like? A photo of a layout? Just drag and drop the image right into Claude Code, and it can see it and work from it. Instead of typing a paragraph trying to explain a button that looks wrong, show it the screenshot and say 'fix this.' It's faster, clearer, and far less frustrating - especially when words are hard to find. A picture really is worth a thousand prompts. Comment SHOW and I'll send you my favorite ways to use images with Claude. See you tomorrow!",
    caption: "Day 14 of Claude Code Summer. Don't describe it - SHOW it. Drag a screenshot or photo right into Claude Code and it works from the picture. Got an error? Show it and say 'fix this.' Comment SHOW for my favorite ways to use images.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said SHOW 🙌 Here's my favorite ways to use images with Claude Code — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-15-undo-rewind-checkpoints": {
    script: "Never fear a mistake again. The thing that scares beginners most is breaking something. Good news: Claude Code has a safety net. As you work, it quietly saves checkpoints - little save points along the way. If Claude makes a change you don't like, you can rewind: it undoes the changes and takes you back to how things were, including earlier in your conversation. So you can experiment freely - try a bold idea, and if it goes sideways, just rewind and you're back on solid ground. This one feature takes all the fear out of building. Comment UNDO and I'll show you exactly how to rewind, step by step.",
    caption: "Day 15 of Claude Code Summer. Scared of breaking something? Claude Code saves checkpoints as you go - and you can rewind to undo changes and step back in the conversation. Experiment freely; if it goes sideways, rewind. Comment UNDO for the step-by-step.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said UNDO 🙌 Here's the step-by-step on rewind and checkpoints — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-16-make-claude-think-harder": {
    script: "Make Claude think harder. Sometimes you're not asking for something simple - you're asking for something tricky that needs real reasoning. Claude Code can do exactly that. When a task is complex, you can ask Claude to think it through more deeply before answering - words like 'think' or 'think hard' in your prompt tell it to slow down and reason step by step instead of rushing. You'll often get a noticeably better plan or solution. Use it for the hard stuff: tricky bugs, big decisions, anything where a quick answer won't cut it. For everyday tasks, normal speed is fine - save the deep thinking for when it counts. Comment THINK and I'll send you the exact phrases that trigger it.",
    caption: "Day 16 of Claude Code Summer. For tricky tasks, make Claude think harder. Add 'think' or 'think hard' to your prompt and it slows down and reasons step by step - better plans, better fixes. Save it for the hard stuff. Comment THINK for the exact phrases.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said THINK 🙌 Here's the exact phrases that make Claude think harder — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-17-a-claude-md-for-every-project": {
    script: "A different CLAUDE.md for every project. Remember CLAUDE.md, the memo file Claude reads at the start of each session? Here's the next level: keep a different one in each project. Why does that matter? Every project has its own rules - one might need a certain style, another a specific way of doing things. By giving each project its own CLAUDE.md, Claude instantly knows the rules for whatever you're working on, without you re-explaining. Open project A, it follows A's rules; open project B, it follows B's. You can also keep personal preferences that apply everywhere. It's like leaving the perfect set of instructions in every room. Comment RULES and I'll send you a simple CLAUDE.md template to copy.",
    caption: "Day 17 of Claude Code Summer. Give every project its own CLAUDE.md so Claude knows that project's rules the moment you open it - no re-explaining. Plus personal preferences that apply everywhere. Comment RULES for a copy-paste template.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said RULES 🙌 Here's a copy-paste CLAUDE.md template — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-18-automate-with-hooks": {
    script: "Automate the boring stuff with hooks. Once you're comfortable, here's a power feature: hooks. A hook tells Claude Code, 'every time this happens, automatically do that.' For example: every time Claude edits a file, automatically run your tests. Or every time you finish a task, automatically tidy up. You set the rule once, and Claude handles it in the background - no reminding, no clicking. It's how you turn repetitive steps into things that just happen on their own. You don't need this on day one, but when you find yourself doing the same little step over and over, that's your sign to make it a hook. Comment AUTO and I'll send you a few beginner-friendly hook ideas.",
    caption: "Day 18 of Claude Code Summer. Automate the boring stuff with hooks: 'every time X happens, automatically do Y' - like running tests after each edit. Set it once, Claude handles it. Comment AUTO for beginner-friendly hook ideas.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said AUTO 🙌 Here's beginner-friendly automation hook ideas — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-19-where-to-run-claude-code": {
    script: "Where can you use Claude Code? You're not stuck in one place - Claude Code meets you where you work. The classic spot is your terminal, that black screen we set up. But you can also use it inside a code editor like VS Code, so it sits right next to your files. There's the Claude desktop app if you'd rather have a friendly window. And you can even use it on the web from your browser. Same Claude, same abilities - just pick the home that feels most comfortable. If the terminal feels intimidating, start in the desktop app and work your way in. Comment WHERE and I'll help you pick the best starting point for you.",
    caption: "Day 19 of Claude Code Summer. Claude Code meets you where you work: the terminal, an editor like VS Code, the desktop app, or right in your browser. Same Claude - pick your comfiest home. Comment WHERE and I'll help you choose.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said WHERE 🙌 Here's help picking the best place to run Claude Code — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-20-your-first-real-project": {
    script: "Your first real project, the Claude Code way. Today we put it all together. The secret isn't typing 'build me an app' - it's guiding Claude through four steps: explore, plan, code, commit. First, explore: tell Claude what you want and let it look around and ask questions. Second, plan: switch to plan mode and let it write out the approach before touching anything. Third, code: approve the plan and let it build, reviewing changes with /diff as you go. Fourth, commit: save your work so it's safe. Go slow, approve each step, and you'll be amazed what you can make - even with zero coding background. Comment PROJECT and I'll send you a simple first-project idea to try this weekend.",
    caption: "Day 20 of Claude Code Summer. Your first real project, the Claude Code way: explore -> plan -> code -> commit. Approve each step and you'll amaze yourself - even with zero coding background. Comment PROJECT for a simple first idea to try this weekend.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said PROJECT 🙌 Here's a simple first-project idea to try this weekend — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-21-save-your-work-git-github": {
    script: "Save your work safely - Git and GitHub, the simple version. Don't let the names scare you. Git is just a way to save snapshots of your work so you can always go back. GitHub is the website where those snapshots live online, safe and shareable. The lovely part: you don't have to learn the commands - you can ask Claude Code in plain English. 'Save my work,' or 'commit these changes with a note about what I did,' and Claude handles it. 'Put this on GitHub for me,' and it walks you through. It's like hitting save, but for your whole project, with a history you can always rewind to. Comment GIT and I'll send you the three plain-English phrases I use most.",
    caption: "Day 21 of Claude Code Summer. Save your work without learning commands. Git = snapshots of your work; GitHub = where they live online. Just tell Claude in plain English: 'commit my changes' or 'put this on GitHub.' Comment GIT for the 3 phrases I use most.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said GIT 🙌 Here's the 3 plain-English Git phrases I use most — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-22-review-changes-with-diff": {
    script: "Always look before you save - the /diff habit. Quick but important one. Before you save your work, it's smart to see exactly what changed - and Claude Code makes that easy with /diff. Type it, and Claude shows you every change it made this session: what was added, what was removed, line by line. Why bother? Because it keeps you in control - you approve what's good and catch anything you didn't intend before it's locked in. I treat it like proofreading: review with /diff, then save. Two seconds of checking saves a lot of headaches later. Comment REVIEW and I'll show you how to read a diff without the tech overwhelm.",
    caption: "Day 22 of Claude Code Summer. Before you save, look. Type /diff to see every change Claude made - added and removed, line by line - so you approve the good and catch the rest. Review, then save. Comment REVIEW to read a diff without the overwhelm.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said REVIEW 🙌 Here's how to read a /diff without the tech overwhelm — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-23-pick-up-where-you-left-off": {
    script: "Pick up right where you left off. Ever close your laptop mid-project and worry you've lost your place? With Claude Code, you haven't. You can resume a past session and Claude remembers the whole conversation - what you were building, the decisions you made, where you stopped. Just reopen and continue, instead of starting over and re-explaining everything. It's like a bookmark for your work. So you can build in little pockets of time - twenty minutes here, an hour there - and never lose momentum. Comment RESUME and I'll show you the exact way to jump back in.",
    caption: "Day 23 of Claude Code Summer. Closed your laptop mid-project? You haven't lost your place. Resume a past session and Claude remembers the whole thing - build in little pockets of time, never start over. Comment RESUME for the exact way to jump back in.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said RESUME 🙌 Here's the exact way to resume a past session — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-24-don-t-get-lost-in-a-big-project": {
    script: "Don't get lost in a big project. As your project grows - lots of files, lots of folders - it's easy to feel lost. Claude Code is brilliant here. Instead of you hunting around, just ask: 'where is the part that does the login?' or 'explain how this project is organized.' Claude reads through everything and points you to the right place in plain English. Remember /init too - it has Claude study the whole project and take notes up front. This is a lifesaver when you've inherited something someone else built, or you're returning to your own work weeks later. Comment BIG and I'll share my go-to questions for understanding any project fast.",
    caption: "Day 24 of Claude Code Summer. Big project, can't find anything? Just ask: 'where's the login part?' or 'how is this organized?' Claude reads it all and points you there. /init helps too. Comment BIG for my go-to questions to understand any project fast.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said BIG 🙌 Here's my go-to questions to understand any big project fast — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-25-debugging-with-claude": {
    script: "Let Claude fix your mistakes. Something broke? Don't panic - this is where Claude Code shines. Paste the error message, or just say 'this isn't working,' and Claude reads it, figures out what went wrong, and fixes it - explaining what happened so you learn too. You can even show it a screenshot of the error. The trick is to give it details: what you expected, and what actually happened. Then let it investigate, try a fix, and check its own work. Bugs stop being scary when you've got a patient expert who'll track them down for you. Comment FIX and I'll send you the exact words to say when something breaks.",
    caption: "Day 25 of Claude Code Summer. Something broke? Paste the error or say 'this isn't working' - Claude finds the problem, fixes it, and explains so you learn. You can even show it a screenshot. Comment FIX for the exact words to say when something breaks.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said FIX 🙌 Here's the exact words to say when something breaks — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-26-shortcuts-tips": {
    script: "Little shortcuts that make Claude Code feel easy. A handful of small tricks that make a big difference. Shift+Tab cycles your permission modes - normal, auto-accept, plan. The up arrow brings back your last message so you can tweak it instead of retyping. Type '/' anytime to open the command menu. Press Escape to stop Claude mid-task if it's heading the wrong way - then steer it. And drag any image straight in to show, not tell. None of these are complicated, but together they make the whole thing feel smooth instead of clunky. Comment TIPS and I'll send you my one-page shortcut cheat sheet. See you tomorrow!",
    caption: "Day 26 of Claude Code Summer. Little shortcuts, big difference: Shift+Tab (modes), up arrow (reuse last message), '/' (command menu), Esc (stop and steer), drag an image to show not tell. Comment TIPS for my one-page cheat sheet.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said TIPS 🙌 Here's my one-page shortcuts cheat sheet — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-27-keep-your-costs-low": {
    script: "Smart habits to keep your costs low. Claude Code is generous on a Pro plan, but a few habits keep things efficient. One: start fresh for new tasks with /clear, so Claude isn't carrying old baggage. Two: when a session gets long, run /compact to trim it down. Three: check /cost now and then to stay aware. Four: be clear and specific in your prompts - the less back-and-forth, the better. None of this is penny-pinching; it's about keeping Claude fast and focused. Tidy sessions are happy sessions. Comment SAVE and I'll send you my simple weekly routine. See you tomorrow!",
    caption: "Day 27 of Claude Code Summer. Keep Claude fast and your costs low: /clear for new tasks, /compact on long sessions, check /cost, and be specific in prompts. Tidy sessions = happy sessions. Comment SAVE for my simple weekly routine.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said SAVE 🙌 Here's my simple weekly cost-saving routine — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-28-beginner-mistakes-to-avoid": {
    script: "Beginner mistakes to avoid with Claude Code. Let me save you some headaches. Mistake one: telling it to build before it understands the goal - always let it explore and plan first. Mistake two: skipping plan mode on anything complex - that's where the magic is. Mistake three: never checking changes - use /diff before you save. Mistake four: letting one giant conversation run forever - clear and compact to keep it sharp. Mistake five: being vague - the clearer you are, the better Claude is. Avoid these five and you're already ahead of most people. Comment MISTAKES and I'll send you the full checklist. See you tomorrow!",
    caption: "Day 28 of Claude Code Summer. 5 beginner mistakes to avoid: building before planning, skipping plan mode, never checking changes (/diff!), letting one chat run forever, and being vague. Avoid these and you're ahead of most. Comment MISTAKES for the full checklist.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said MISTAKES 🙌 Here's the full beginner-mistakes checklist — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-29-my-favorite-workflow-start-to-finish": {
    script: "My favorite Claude Code workflow, start to finish. Here's exactly how I work, every time. I open Claude Code and start in plan mode. I describe what I want and answer its questions. I read the plan it gives me and tweak anything off. Then I approve it and let Claude build, watching the changes with /diff. When it's done, I ask it to verify - run the tests, check it works. Then I save with a plain-English commit. If anything's off, I rewind and adjust. Explore, plan, code, check, save. That rhythm turns even big ideas into calm, steady progress. Comment FLOW and I'll send you this workflow as a printable one-pager.",
    caption: "Day 29 of Claude Code Summer. My exact workflow: plan mode -> describe & answer questions -> review the plan -> approve & build (watch with /diff) -> verify -> save -> rewind if needed. Explore, plan, code, check, save. Comment FLOW for the printable one-pager.",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said FLOW 🙌 Here's my full workflow as a printable one-pager — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
  "ccs-30-recap-what-to-learn-next": {
    script: "That's a wrap on Claude Code Summer! Thirty days ago, Claude Code might have sounded intimidating. Now you know what it is, how to install it, how it works, how to prompt it, the workflow that keeps you sane, the slash commands, CLAUDE.md, subagents, connecting your tools, and so much more. The biggest lesson? You don't need a tech background - you need curiosity and a willingness to guide it step by step. So keep building. Pick one small project and make it real. And if this series helped you, save it, share it with a friend who thinks coding isn't for them, and tell them it's never too late to start. Thank you for spending the summer with me - class dismissed! Comment NEXT and I'll send you where to go from here.",
    caption: "Day 30 - that's a wrap on Claude Code Summer! You now know what Claude Code is, how to install and use it, the workflow, slash commands, CLAUDE.md, subagents, MCP and more - no tech background required. Keep building, save this, share it with a friend, and comment NEXT for where to go from here. Thank you for spending the summer with me!",
    hashtags: ["ClaudeCode", "ClaudeCodeSummer", "LearnToCode", "Anthropic", "BuildWithClaude", "AItools", "CodingForBeginners", "TechTok", "AIforEveryone", "NoCode", "50plusandlearning"],
    dmReply: "Yes! You said NEXT 🙌 Here's where to go next after Claude Code Summer — tap the button below and it's yours. Follow along with all 30 days of Claude Code Summer, and reply here if you get stuck — I read every message! 💬",
  },
};
